services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
      - '--enable-feature=remote-write-receiver'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  k6:
    image: grafana/k6:latest
    command: run /scripts/basic-test.js
    volumes:
      - ./scripts:/scripts
      - ./results:/results
    environment:
      - K6_OUT=json=/results/result.json
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
    network_mode: host
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    sysctls:
      - net.core.somaxconn=65535
      - net.core.netdev_max_backlog=5000
      - net.ipv4.tcp_max_syn_backlog=65535
      - net.ipv4.tcp_fin_timeout=30
      - net.ipv4.tcp_keepalive_time=1200
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.ip_local_port_range=1024 65535
    privileged: true
    depends_on:
      - prometheus

volumes:
  grafana-storage:
