services:
  k6:
    image: grafana/k6:latest
    command: run /scripts/basic-test.js
    volumes:
      - ./scripts:/scripts
      - ./results:/results
    environment:
      - K6_OUT=json=/results/result.json
    network_mode: host
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    sysctls:
      - net.core.somaxconn=65535
      - net.core.netdev_max_backlog=5000
      - net.ipv4.tcp_max_syn_backlog=65535
      - net.ipv4.tcp_fin_timeout=30
      - net.ipv4.tcp_keepalive_time=1200
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.ip_local_port_range=1024 65535
    privileged: true
